//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\Belkis Vasquez\source\repos\RecetaParser\RecetaParser\ProyectoRecetario.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ProyectoRecetarioParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IProyectoRecetarioVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoRecetarioParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ProyectoRecetarioParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoRecetarioParser.receta"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceta([NotNull] ProyectoRecetarioParser.RecetaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoRecetarioParser.nombre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNombre([NotNull] ProyectoRecetarioParser.NombreContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoRecetarioParser.porciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPorciones([NotNull] ProyectoRecetarioParser.PorcionesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoRecetarioParser.tiempoPreparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTiempoPreparacion([NotNull] ProyectoRecetarioParser.TiempoPreparacionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoRecetarioParser.tiempoCoccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTiempoCoccion([NotNull] ProyectoRecetarioParser.TiempoCoccionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoRecetarioParser.calorias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalorias([NotNull] ProyectoRecetarioParser.CaloriasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoRecetarioParser.ingredientes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIngredientes([NotNull] ProyectoRecetarioParser.IngredientesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoRecetarioParser.det_ingredientes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDet_ingredientes([NotNull] ProyectoRecetarioParser.Det_ingredientesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoRecetarioParser.elaboracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElaboracion([NotNull] ProyectoRecetarioParser.ElaboracionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoRecetarioParser.det_elaboracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDet_elaboracion([NotNull] ProyectoRecetarioParser.Det_elaboracionContext context);
}
