//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\Belkis Vasquez\source\repos\RecetaParser\RecetaParser\ProyectoRecetario.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class ProyectoRecetarioLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, REC_LBL=2, POR_LBL=3, TIEMP_PREP_LBL=4, TIEMP_COC_LBL=5, CAL_LBL=6, 
		INGR_LBL=7, ELAB_LBL=8, SEP=9, SP=10, COMA=11, PAR=12, NUM=13, TEXT=14, 
		WORD=15, GUION=16, NEWLINE=17;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "REC_LBL", "POR_LBL", "TIEMP_PREP_LBL", "TIEMP_COC_LBL", "CAL_LBL", 
		"INGR_LBL", "ELAB_LBL", "SEP", "SP", "COMA", "PAR", "NUM", "TEXT", "WORD", 
		"GUION", "NEWLINE"
	};


	public ProyectoRecetarioLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ProyectoRecetarioLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "' '", "'RECETA'", "'PORCIONES'", "'TIEMPO PREPARACION'", "'TIEMPO COCCION'", 
		"'CALORIAS'", "'INGREDIENTES'", "'ELABORACION'", null, null, "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "REC_LBL", "POR_LBL", "TIEMP_PREP_LBL", "TIEMP_COC_LBL", "CAL_LBL", 
		"INGR_LBL", "ELAB_LBL", "SEP", "SP", "COMA", "PAR", "NUM", "TEXT", "WORD", 
		"GUION", "NEWLINE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ProyectoRecetario.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ProyectoRecetarioLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x13', '\xBA', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x5', '\n', '~', '\n', '\n', 
		'\x3', '\n', '\x3', '\n', '\x5', '\n', '\x82', '\n', '\n', '\x3', '\v', 
		'\x6', '\v', '\x85', '\n', '\v', '\r', '\v', '\xE', '\v', '\x86', '\x3', 
		'\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x5', '\r', '\x8D', '\n', 
		'\r', '\x3', '\xE', '\a', '\xE', '\x90', '\n', '\xE', '\f', '\xE', '\xE', 
		'\xE', '\x93', '\v', '\xE', '\x3', '\xE', '\x6', '\xE', '\x96', '\n', 
		'\xE', '\r', '\xE', '\xE', '\xE', '\x97', '\x3', '\xE', '\x5', '\xE', 
		'\x9B', '\n', '\xE', '\x3', '\xE', '\a', '\xE', '\x9E', '\n', '\xE', '\f', 
		'\xE', '\xE', '\xE', '\xA1', '\v', '\xE', '\x3', '\xE', '\x5', '\xE', 
		'\xA4', '\n', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\a', '\xF', '\xAA', '\n', '\xF', '\f', '\xF', '\xE', '\xF', '\xAD', 
		'\v', '\xF', '\x3', '\x10', '\x6', '\x10', '\xB0', '\n', '\x10', '\r', 
		'\x10', '\xE', '\x10', '\xB1', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x2', '\x2', 
		'\x13', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', 
		'\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', 
		'\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', 
		'\x12', '#', '\x13', '\x3', '\x2', '\x5', '\x3', '\x2', '\x32', ';', '\x5', 
		'\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x5', '\x2', '\v', 
		'\f', '\xF', '\xF', '\"', '\"', '\x2', '\xC4', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '%', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\a', '.', '\x3', '\x2', '\x2', '\x2', 
		'\t', '\x38', '\x3', '\x2', '\x2', '\x2', '\v', 'K', '\x3', '\x2', '\x2', 
		'\x2', '\r', 'Z', '\x3', '\x2', '\x2', '\x2', '\xF', '\x63', '\x3', '\x2', 
		'\x2', '\x2', '\x11', 'p', '\x3', '\x2', '\x2', '\x2', '\x13', '}', '\x3', 
		'\x2', '\x2', '\x2', '\x15', '\x84', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'\x88', '\x3', '\x2', '\x2', '\x2', '\x19', '\x8A', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x91', '\x3', '\x2', '\x2', '\x2', '\x1D', '\xA5', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', '\xAF', '\x3', '\x2', '\x2', '\x2', '!', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '#', '\xB6', '\x3', '\x2', '\x2', 
		'\x2', '%', '&', '\a', '\"', '\x2', '\x2', '&', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '\'', '(', '\a', 'T', '\x2', '\x2', '(', ')', '\a', 'G', '\x2', 
		'\x2', ')', '*', '\a', '\x45', '\x2', '\x2', '*', '+', '\a', 'G', '\x2', 
		'\x2', '+', ',', '\a', 'V', '\x2', '\x2', ',', '-', '\a', '\x43', '\x2', 
		'\x2', '-', '\x6', '\x3', '\x2', '\x2', '\x2', '.', '/', '\a', 'R', '\x2', 
		'\x2', '/', '\x30', '\a', 'Q', '\x2', '\x2', '\x30', '\x31', '\a', 'T', 
		'\x2', '\x2', '\x31', '\x32', '\a', '\x45', '\x2', '\x2', '\x32', '\x33', 
		'\a', 'K', '\x2', '\x2', '\x33', '\x34', '\a', 'Q', '\x2', '\x2', '\x34', 
		'\x35', '\a', 'P', '\x2', '\x2', '\x35', '\x36', '\a', 'G', '\x2', '\x2', 
		'\x36', '\x37', '\a', 'U', '\x2', '\x2', '\x37', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x38', '\x39', '\a', 'V', '\x2', '\x2', '\x39', ':', '\a', 'K', 
		'\x2', '\x2', ':', ';', '\a', 'G', '\x2', '\x2', ';', '<', '\a', 'O', 
		'\x2', '\x2', '<', '=', '\a', 'R', '\x2', '\x2', '=', '>', '\a', 'Q', 
		'\x2', '\x2', '>', '?', '\a', '\"', '\x2', '\x2', '?', '@', '\a', 'R', 
		'\x2', '\x2', '@', '\x41', '\a', 'T', '\x2', '\x2', '\x41', '\x42', '\a', 
		'G', '\x2', '\x2', '\x42', '\x43', '\a', 'R', '\x2', '\x2', '\x43', '\x44', 
		'\a', '\x43', '\x2', '\x2', '\x44', '\x45', '\a', 'T', '\x2', '\x2', '\x45', 
		'\x46', '\a', '\x43', '\x2', '\x2', '\x46', 'G', '\a', '\x45', '\x2', 
		'\x2', 'G', 'H', '\a', 'K', '\x2', '\x2', 'H', 'I', '\a', 'Q', '\x2', 
		'\x2', 'I', 'J', '\a', 'P', '\x2', '\x2', 'J', '\n', '\x3', '\x2', '\x2', 
		'\x2', 'K', 'L', '\a', 'V', '\x2', '\x2', 'L', 'M', '\a', 'K', '\x2', 
		'\x2', 'M', 'N', '\a', 'G', '\x2', '\x2', 'N', 'O', '\a', 'O', '\x2', 
		'\x2', 'O', 'P', '\a', 'R', '\x2', '\x2', 'P', 'Q', '\a', 'Q', '\x2', 
		'\x2', 'Q', 'R', '\a', '\"', '\x2', '\x2', 'R', 'S', '\a', '\x45', '\x2', 
		'\x2', 'S', 'T', '\a', 'Q', '\x2', '\x2', 'T', 'U', '\a', '\x45', '\x2', 
		'\x2', 'U', 'V', '\a', '\x45', '\x2', '\x2', 'V', 'W', '\a', 'K', '\x2', 
		'\x2', 'W', 'X', '\a', 'Q', '\x2', '\x2', 'X', 'Y', '\a', 'P', '\x2', 
		'\x2', 'Y', '\f', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', '\x45', 
		'\x2', '\x2', '[', '\\', '\a', '\x43', '\x2', '\x2', '\\', ']', '\a', 
		'N', '\x2', '\x2', ']', '^', '\a', 'Q', '\x2', '\x2', '^', '_', '\a', 
		'T', '\x2', '\x2', '_', '`', '\a', 'K', '\x2', '\x2', '`', '\x61', '\a', 
		'\x43', '\x2', '\x2', '\x61', '\x62', '\a', 'U', '\x2', '\x2', '\x62', 
		'\xE', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\a', 'K', '\x2', '\x2', 
		'\x64', '\x65', '\a', 'P', '\x2', '\x2', '\x65', '\x66', '\a', 'I', '\x2', 
		'\x2', '\x66', 'g', '\a', 'T', '\x2', '\x2', 'g', 'h', '\a', 'G', '\x2', 
		'\x2', 'h', 'i', '\a', '\x46', '\x2', '\x2', 'i', 'j', '\a', 'K', '\x2', 
		'\x2', 'j', 'k', '\a', 'G', '\x2', '\x2', 'k', 'l', '\a', 'P', '\x2', 
		'\x2', 'l', 'm', '\a', 'V', '\x2', '\x2', 'm', 'n', '\a', 'G', '\x2', 
		'\x2', 'n', 'o', '\a', 'U', '\x2', '\x2', 'o', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'p', 'q', '\a', 'G', '\x2', '\x2', 'q', 'r', '\a', 'N', '\x2', 
		'\x2', 'r', 's', '\a', '\x43', '\x2', '\x2', 's', 't', '\a', '\x44', '\x2', 
		'\x2', 't', 'u', '\a', 'Q', '\x2', '\x2', 'u', 'v', '\a', 'T', '\x2', 
		'\x2', 'v', 'w', '\a', '\x43', '\x2', '\x2', 'w', 'x', '\a', '\x45', '\x2', 
		'\x2', 'x', 'y', '\a', 'K', '\x2', '\x2', 'y', 'z', '\a', 'Q', '\x2', 
		'\x2', 'z', '{', '\a', 'P', '\x2', '\x2', '{', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '|', '~', '\x5', '\x15', '\v', '\x2', '}', '|', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\x3', '\x2', 
		'\x2', '\x2', '\x7F', '\x81', '\a', '<', '\x2', '\x2', '\x80', '\x82', 
		'\x5', '\x15', '\v', '\x2', '\x81', '\x80', '\x3', '\x2', '\x2', '\x2', 
		'\x81', '\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x14', '\x3', '\x2', 
		'\x2', '\x2', '\x83', '\x85', '\a', '\"', '\x2', '\x2', '\x84', '\x83', 
		'\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'\x86', '\x84', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\x3', '\x2', 
		'\x2', '\x2', '\x87', '\x16', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', 
		'\a', '.', '\x2', '\x2', '\x89', '\x18', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8C', '\a', '+', '\x2', '\x2', '\x8B', '\x8D', '\x5', '\x15', '\v', 
		'\x2', '\x8C', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x8E', 
		'\x90', '\x5', '\x15', '\v', '\x2', '\x8F', '\x8E', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x93', '\x3', '\x2', '\x2', '\x2', '\x91', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x92', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x93', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '\x94', '\x96', '\t', '\x2', '\x2', '\x2', '\x95', '\x94', '\x3', 
		'\x2', '\x2', '\x2', '\x96', '\x97', '\x3', '\x2', '\x2', '\x2', '\x97', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9B', '\a', 
		'\x30', '\x2', '\x2', '\x9A', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9B', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x9E', '\t', '\x2', '\x2', '\x2', '\x9D', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\x9D', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA4', '\x5', '\x15', '\v', '\x2', '\xA3', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x3', '\x2', '\x2', 
		'\x2', '\xA4', '\x1C', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xAB', '\x5', 
		'\x1F', '\x10', '\x2', '\xA6', '\xA7', '\x5', '\x15', '\v', '\x2', '\xA7', 
		'\xA8', '\x5', '\x1F', '\x10', '\x2', '\xA8', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '\xA9', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAD', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\xAC', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\xAD', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xB0', '\t', 
		'\x3', '\x2', '\x2', '\xAF', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xB0', 
		'\xB1', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xAF', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB2', ' ', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xB4', '\a', '/', '\x2', '\x2', '\xB4', 
		'\xB5', '\x5', '\x15', '\v', '\x2', '\xB5', '\"', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\xB7', '\t', '\x4', '\x2', '\x2', '\xB7', '\xB8', '\x3', 
		'\x2', '\x2', '\x2', '\xB8', '\xB9', '\b', '\x12', '\x2', '\x2', '\xB9', 
		'$', '\x3', '\x2', '\x2', '\x2', '\xE', '\x2', '}', '\x81', '\x86', '\x8C', 
		'\x91', '\x97', '\x9A', '\x9F', '\xA3', '\xAB', '\xB1', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
